Repository 9oormthon-univ/2024_DANPOONG_TEAM_4_BE, pull requests merged in 2024-11, with the labels that each got.

#9 상점 상세조회 API 작성
  .gitignore
  src/main/java/com/univ/sohwakhaeng/enterprise/Enterprise.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/EnterpriseController.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/dto/EnterpriseDto.java
  src/main/java/com/univ/sohwakhaeng/enterprise/exception/EnterpriseNotFoundException.java
  src/main/java/com/univ/sohwakhaeng/enterprise/repository/EnterpriseRepository.java
  src/main/java/com/univ/sohwakhaeng/enterprise/service/EnterpriseService.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/ErrorCode.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/product/Product.java
  src/main/java/com/univ/sohwakhaeng/product/api/dto/ProductDto.java
  src/main/resources/application-dev.yml
Labels: feat

#15 장바구니 등록 API 작성
  src/main/java/com/univ/sohwakhaeng/auth/domain/PrincipalDetails.java
  src/main/java/com/univ/sohwakhaeng/cart/Cart.java
  src/main/java/com/univ/sohwakhaeng/cart/api/CartController.java
  src/main/java/com/univ/sohwakhaeng/cart/api/dto/CartRequestDto.java
  src/main/java/com/univ/sohwakhaeng/cart/repository/CartRepository.java
  src/main/java/com/univ/sohwakhaeng/cart/service/CartService.java
  src/main/java/com/univ/sohwakhaeng/enterprise/Category.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/EnterpriseController.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/dto/EnterpriseDetailDto.java
  src/main/java/com/univ/sohwakhaeng/enterprise/service/EnterpriseService.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/ErrorCode.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/item/Item.java
  src/main/java/com/univ/sohwakhaeng/item/api/dto/ItemRequestDto.java
  src/main/java/com/univ/sohwakhaeng/item/repository/ItemRepository.java
  src/main/java/com/univ/sohwakhaeng/item/service/ItemService.java
  src/main/java/com/univ/sohwakhaeng/product/api/dto/ProductResponseDto.java
  src/main/java/com/univ/sohwakhaeng/product/exception/ProductNotFoundException.java
  src/main/java/com/univ/sohwakhaeng/product/repository/ProductRepository.java
  src/main/java/com/univ/sohwakhaeng/product/service/ProductService.java
Labels: feat

#18 계약 요청 기능 구현 및 파라미터 버그 해결
  src/main/java/com/univ/sohwakhaeng/auth/api/AuthController.java
  src/main/java/com/univ/sohwakhaeng/contract/api/ContractController.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/Contract.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/ContractProducts.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/MethodToTake.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/repository/ContractProductsRepository.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/repository/ContractRepository.java
  src/main/java/com/univ/sohwakhaeng/contract/dto/ContractReqDto.java
  src/main/java/com/univ/sohwakhaeng/contract/dto/ProductDto.java
  src/main/java/com/univ/sohwakhaeng/contract/service/ContractService.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/global/config/SecurityConfig.java
  src/main/resources/application-dev.yml
Labels: feat, bug fix

#22 계약 조회 기능 구현
  src/main/java/com/univ/sohwakhaeng/contract/api/ContractController.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractDetailDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractProducsResDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractReqDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractsInfoDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ProductDto.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/Contract.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/ContractProducts.java
  src/main/java/com/univ/sohwakhaeng/contract/domain/repository/ContractRepository.java
  src/main/java/com/univ/sohwakhaeng/contract/service/ContractService.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
Labels: feat

#23 장바구니 전체 조회 api 작성
  src/main/java/com/univ/sohwakhaeng/cart/api/CartController.java
  src/main/java/com/univ/sohwakhaeng/cart/api/dto/CartResponseDto.java
  src/main/java/com/univ/sohwakhaeng/cart/repository/CartRepository.java
  src/main/java/com/univ/sohwakhaeng/cart/service/CartService.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/item/api/dto/ItemRequestDto.java
Labels: feat

#30 Swagger 요청, 응답 DTO 예시 값 설정
  src/main/java/com/univ/sohwakhaeng/auth/api/dto/TokenDto.java
  src/main/java/com/univ/sohwakhaeng/cart/api/dto/CartRequestDto.java
  src/main/java/com/univ/sohwakhaeng/cart/api/dto/CartResponseDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractDetailDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractProducsResDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractReqDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ContractsInfoDto.java
  src/main/java/com/univ/sohwakhaeng/contract/api/dto/ProductDto.java
  src/main/java/com/univ/sohwakhaeng/contract/service/ContractService.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/dto/EnterpriseDetailDto.java
  src/main/java/com/univ/sohwakhaeng/enterprise/api/dto/EnterpriseOverviewDto.java
  src/main/java/com/univ/sohwakhaeng/item/api/dto/ItemRequestDto.java
  src/main/java/com/univ/sohwakhaeng/item/api/dto/ItemResponseDto.java
  src/main/java/com/univ/sohwakhaeng/product/api/dto/ProductResponseDto.java
Labels: feat

#36 Fix: 키 타입 수정
  src/main/resources/application-prod.yml
Labels: fix

#39 결제 확인 API 작성
  build.gradle
  src/main/java/com/univ/sohwakhaeng/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/ErrorCode.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/global/config/AppConfig.java
  src/main/java/com/univ/sohwakhaeng/payment/api/PaymentController.java
  src/main/java/com/univ/sohwakhaeng/payment/domain/Payment.java
  src/main/java/com/univ/sohwakhaeng/payment/exception/PaymentFailException.java
  src/main/java/com/univ/sohwakhaeng/payment/repository/PaymentRepository.java
  src/main/java/com/univ/sohwakhaeng/payment/service/PaymentService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat

#40 로그인 로직 변경
  src/main/java/com/univ/sohwakhaeng/auth/api/AuthController.java
  src/main/java/com/univ/sohwakhaeng/auth/api/dto/KakaoLoginDto.java
  src/main/java/com/univ/sohwakhaeng/auth/api/dto/KakaoTokenDto.java
  src/main/java/com/univ/sohwakhaeng/auth/domain/KakaoUserInfo.java
  src/main/java/com/univ/sohwakhaeng/auth/domain/OAuth2UserInfo.java
  src/main/java/com/univ/sohwakhaeng/auth/domain/PrincipalDetails.java
  src/main/java/com/univ/sohwakhaeng/auth/service/OAuth2LoginService.java
  src/main/resources/application-dev.yml
Labels: fix

#41 결제 API 도입
  build.gradle
  src/main/java/com/univ/sohwakhaeng/global/common/advice/ControllerExceptionAdvice.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/ErrorCode.java
  src/main/java/com/univ/sohwakhaeng/global/common/exception/SuccessCode.java
  src/main/java/com/univ/sohwakhaeng/global/config/AppConfig.java
  src/main/java/com/univ/sohwakhaeng/payment/api/PaymentController.java
  src/main/java/com/univ/sohwakhaeng/payment/domain/Payment.java
  src/main/java/com/univ/sohwakhaeng/payment/exception/PaymentFailException.java
  src/main/java/com/univ/sohwakhaeng/payment/repository/PaymentRepository.java
  src/main/java/com/univ/sohwakhaeng/payment/service/PaymentService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: fix, feat

#44 #42 Fix : 빈 순환 수정
  src/main/java/com/univ/sohwakhaeng/product/api/ProductController.java
  src/main/java/com/univ/sohwakhaeng/product/service/ProductService.java
Labels: fix
